### Listar 
GET https://localhost:5001/api/folhaPagamento/listar

### Buscar 
GET https://localhost:5001/api/folhaPagamento/buscar/123


### Filtrar
GET https://localhost:5001/api/folhaPagamento/filtrar/